// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-lotteries.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var LOTTERIES = [
  { id: "megasena", name: "Mega-Sena" },
  { id: "lotofacil", name: "Lotof\xE1cil" },
  { id: "quina", name: "Quina" },
  { id: "lotomania", name: "Lotomania" },
  { id: "duplasena", name: "Dupla Sena" },
  { id: "diadesorte", name: "Dia de Sorte" },
  { id: "supersete", name: "Super Sete" },
  { id: "maismilionaria", name: "+Milion\xE1ria" },
  { id: "timemania", name: "Timemania" },
  { id: "federal", name: "Federal" },
  { id: "loteca", name: "Loteca" }
];
var list_lotteries_default = defineTool({
  name: "list_lotteries",
  title: "List lotteries",
  description: "List all Caixa lottery modalities supported by this app, with their machine id and display name.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(LOTTERIES, null, 2) }],
    structuredContent: { lotteries: LOTTERIES }
  })
});

// src/lib/mcp/tools/get-lottery-result.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var LOTTERY_IDS = [
  "megasena",
  "lotofacil",
  "quina",
  "lotomania",
  "duplasena",
  "diadesorte",
  "supersete",
  "maismilionaria",
  "timemania",
  "federal",
  "loteca"
];
var PROJECT_REF = "hpfwrxcfncielvbjmeiv";
var FN_URL = `https://${PROJECT_REF}.supabase.co/functions/v1/fetch-lottery-results`;
var get_lottery_result_default = defineTool2({
  name: "get_lottery_result",
  title: "Get lottery result",
  description: "Fetch the latest official result for a Caixa lottery, or a specific past draw when `concurso` is provided. Returns numbers drawn, prizes, winners, next draw date and estimated prize.",
  inputSchema: {
    lottery: z.enum(LOTTERY_IDS).describe("Lottery id (use list_lotteries to discover valid ids)."),
    concurso: z.number().int().positive().optional().describe("Optional draw number. Omit to get the latest draw.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ lottery, concurso }) => {
    const url = new URL(FN_URL);
    url.searchParams.set("lottery", lottery);
    if (concurso) url.searchParams.set("concurso", String(concurso));
    const res = await fetch(url.toString(), {
      headers: { Accept: "application/json" }
    });
    if (!res.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Failed to fetch result (HTTP ${res.status}).`
          }
        ],
        isError: true
      };
    }
    const data = await res.json();
    if (!data?.result) {
      return {
        content: [{ type: "text", text: "No result found." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data.result, null, 2) }],
      structuredContent: { result: data.result }
    };
  }
});

// src/lib/mcp/tools/get-lottery-history.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var LOTTERY_IDS2 = [
  "megasena",
  "lotofacil",
  "quina",
  "lotomania",
  "duplasena",
  "diadesorte",
  "supersete",
  "maismilionaria",
  "timemania",
  "federal",
  "loteca"
];
var PROJECT_REF2 = "hpfwrxcfncielvbjmeiv";
var FN_URL2 = `https://${PROJECT_REF2}.supabase.co/functions/v1/fetch-lottery-results`;
var get_lottery_history_default = defineTool3({
  name: "get_lottery_history",
  title: "Get lottery history",
  description: "Fetch a batch of recent official draws for a Caixa lottery (most recent first). Useful for statistics, hot/cold analysis and frequency computations.",
  inputSchema: {
    lottery: z2.enum(LOTTERY_IDS2).describe("Lottery id."),
    count: z2.number().int().positive().optional().describe("How many recent draws to return. Server caps this at 200; defaults to 100.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ lottery, count }) => {
    const url = new URL(FN_URL2);
    url.searchParams.set("lottery", lottery);
    url.searchParams.set("mode", "history");
    if (count) url.searchParams.set("count", String(count));
    const res = await fetch(url.toString(), {
      headers: { Accept: "application/json" }
    });
    if (!res.ok) {
      return {
        content: [
          { type: "text", text: `Failed to fetch history (HTTP ${res.status}).` }
        ],
        isError: true
      };
    }
    const data = await res.json();
    const results = Array.isArray(data?.results) ? data.results : [];
    return {
      content: [
        {
          type: "text",
          text: `Returned ${results.length} draws for ${lottery}.`
        }
      ],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lottos-mcp",
  title: "Lottos MCP",
  version: "0.1.0",
  instructions: "Public read-only tools for Caixa Econ\xF4mica Federal lottery results as aggregated by the Lottos app. Use `list_lotteries` to discover valid lottery ids, `get_lottery_result` for the latest or a specific draw, and `get_lottery_history` for a batch of recent draws. This app is NOT officially affiliated with Caixa Econ\xF4mica Federal.",
  tools: [list_lotteries_default, get_lottery_result_default, get_lottery_history_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
